import sqlite3

# Connect to (or create) a SQLite database file
conn = sqlite3.connect('database.db')
cursor = conn.cursor()

# Create a table
cursor.execute('''CREATE TABLE IF NOT EXISTS products
                    (id INTEGER PRIMARY KEY,
                    name TEXT,
                    carbs INTEGER,
                    protein INTEGER,
                    alanine INTEGER,
                    arginine INTEGER,
                    aspartic_acid INTEGER,
                    cystine INTEGER,
                    glutamic_acid INTEGER,
                    glycine INTEGER,
                    histidine INTEGER,
                    hydroxyproline INTEGER,
                    isoleucine INTEGER,
                    leucine INTEGER,
                    lysine INTEGER,
                    methionine INTEGER,
                    phenylalanine INTEGER,
                    proline INTEGER,
                    serine INTEGER,
                    threonine INTEGER,
                    tryptophan INTEGER,
                    tyrosine INTEGER,
                    valine INTEGER,
                    fat INTEGER,
                    satureted_fat INTEGER,
                    trans_fat INTEGER,
                    mono_unsaturated_fat INTEGER,
                    poly_unsaturated_fat INTEGER,
                    omega3 INTEGER,
                    omega6 INTEGER,
                    omega9 INTEGER,
                    cholesterol INTEGER,
                    phytosterol INTEGER,
                    sodium INTEGER,
                    allulose INTEGER,
                    fructose INTEGER,
                    glucose INTEGER,
                    lactose INTEGER,
                    maltose INTEGER,
                    sucrose INTEGER,
                    galactose INTEGER,
                    calories INTEGER,
                    sugar INTEGER,
                    fiber INTEGER,
                    vitamin_a INTEGER,
                    alpha_carotene INTEGER,
                    beta_carotene INTEGER,
                    beta_cryptoxanthin INTEGER,
                    lycopene INTEGER,
                    lutein_zeaxanthin INTEGER,
                    retinol INTEGER,
                    vitamin_b1 INTEGER,
                    vitamin_b2 INTEGER,
                    vitamin_b3 INTEGER,
                    vitamin_b5 INTEGER,
                    vitamin_b6 INTEGER,
                    vitamin_b12 INTEGER,
                    biotin INTEGER,
                    choline INTEGER,
                    folate INTEGER,
                    vitamin_c INTEGER,
                    vitamin_d INTEGER,
                    vitamin_e INTEGER,
                    beta_tocopherol INTEGER,
                    gamma_tocopherol INTEGER,
                    delta_tocopherol INTEGER,
                    vitamin_k INTEGER,
                    calcium INTEGER,
                    chromium INTEGER,
                    copper INTEGER,
                    fluoride INTEGER,
                    iodine INTEGER,\
                    iron INTEGER,
                    magnesium INTEGER,
                    manganese INTEGER,
                    molybdenum INTEGER,
                    phosphorus INTEGER,
                    potassium INTEGER,
                    selenium INTEGER,
                    sodium INTEGER,
                    zinc INTEGER,
                    protein_quality INTEGER,
                    fat_quality INTEGER,
                    carb_quality INTEGER,       
                )''')

conn.commit()
conn.close()
